---
driver:
    name: vagrant
    customize:
      memory: 2048

provisioner:
    name: chef_solo
    require_chef_omnibus: 11.16.0

platforms:
    - name: ubuntu-12.04
    - name: ubuntu-14.04

suites:
    - name: default
      run_list:
          - recipe[chef_kitchen_demo::default]
      attributes:
